---
- include_role:
    name: "k3s"
- include_role:
    name: dashboard
  vars:
    dashboard_user: "dynatrace"
    dashboard_password: "dynatrace"
    dashboard_namespace: "ace"
- include_role:
    name: dt-operator
  vars:
    operator_mode: "cloudNativeFullStack"
    dt_operator_release: "v1.6.0"
- include_role:
    name: gitlab
- include_role:
    name: gitlab
    tasks_from: ensure-user
  vars:
    gitlab_user_email: "matthew.wheeler@dynatrace.test"
    gitlab_user_name: "Matthew Wheeler"
    gitlab_user_username: "MatthewWheeler"
    gitlab_user_password: "mattwheelz"
    gitlab_helm_chart_version: "9.1.2"
- name: Create logging directory
  ansible.builtin.file:
    path: /home/dt_training/init_logs
    state: directory
    mode: '0755'
- name: Pod Status Check
  ansible.builtin.shell: |
    kubectl get pods -n dynatrace >> dtPods.log 
    kubectl get pods -n gitlab >> gitlab.log
    kubectl get ingress -n gitlab -o json | jq '.items[3].spec.rules[0].host' | sed 's/"//g' >> links.txt
  args:
    executable: /bin/bash
    chdir: /home/dt_training/init_logs

