---
- include_role:
    name: "k3s"
- include_role:
    name: dashboard
  vars:
    dashboard_user: "dynatrace"
    dashboard_password: "dynatrace"
    dashboard_namespace: "ace"
- include_role:
    name: dt-operator
  vars:
    operator_mode: "cloudNativeFullStack"
    dt_operator_release: "v1.6.0"
- include_role:
    name: gitlab
- include_role:
    name: gitlab
    tasks_from: ensure-user
  vars:
    gitlab_user_email: "matthew.wheeler@dynatrace.test"
    gitlab_user_name: "Matthew Wheeler"
    gitlab_user_username: "MatthewWheeler"
    gitlab_user_password: "mattwheelz"
    gitlab_helm_chart_version: "9.1.2"
- name: ansibletest
  ansible.builtin.shell:
    chdir: /home/dt_training
    cmd: ls -l | sudo tee -a output.txt
    executable: /bin/bash
    cmd: kubectl get pods -n dynatrace | sudo tee -a output.txt
    cmd: kubectl get pods -n gitlab | sudo tee -a output.txt
    cmd: apt-add-repository --yes --update ppa:ansible/ansible | sudo tee -a output.txt
    cmd: apt install ansible -y | sudo tee -a output.txt